WebApplication/Controllers/DriverShipmentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using PackageDelivery.Core;
using PackageDelivery.Data;
using PackageDelivery.Domain.Entities;
using PackageDelivery.WebApplication.Models;

namespace PackageDelivery.WebApplication.Controllers
{
    [Authorize(Roles = UserRoles.DRIVER)]
    public class DriverShipmentsController : Controller {
        private readonly PackageDeliveryContext _context;
        private readonly UserManager<User> _userManager;

        public DriverShipmentsController(PackageDeliveryContext context, UserManager<User> userManager) {
            _context = context;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index() {
            var user = await _userManager.GetUserAsync(HttpContext.User);
            
            var packageDeliveryContext = _context.Shipments
                .Where(o => o.UserId == user.Id &&
                o.ShipmentState != ShipmentState.WaitingForManagerApprovalToStartDelivery &&
                o.ShipmentState != ShipmentState.WaitingForManagerApprovalToStartPickUp)
                .Include(s => s.User)
                .Include(s => s.PickUpOrders)
                .Include(s => s.DeliveryOrders)
                .Include(s => s.Vehicle);

            return View("~/Views/Shipments/Index.cshtml", await packageDeliveryContext.ToListAsync());
        }

        public async Task<IActionResult> Details(int? id) {
            if (id == null) {
                return NotFound();
            }

            var shipment = await _context.Shipments
                .Include(s => s.User)
                .Include(s => s.Vehicle)
                .ThenInclude(o => o.PickUpPoint.Address)
                .Include(s => s.PickUpOrders)
                .ThenInclude(o => o.PickUpAddress)
                .Include(s => s.PickUpOrders)
                .ThenInclude(o => o.DeliveryAddress)
                .Include(s => s.DeliveryOrders)
                .ThenInclude(o => o.PickUpAddress)
                .Include(s => s.DeliveryOrders)
                .ThenInclude(o => o.DeliveryAddress)
                .SingleOrDefaultAsync(m => m.ShipmentId == id);
            if (shipment == null) {
                return NotFound();
            }

            List<WayPoint> wayPoints;

            if (shipment.IsPickUp()) {
                wayPoints = shipment.PickUpOrders
                    .Select(o => new WayPoint {Location = o.PickUpAddress.ToString(), StopOver = true}).ToList();
            } else {
                wayPoints = shipment.DeliveryOrders
                    .Select(o => new WayPoint { Location = o.DeliveryAddress.ToString(), StopOver = true }).ToList();
            }

            var shipmentDetailsViewModel = new ShipmentDetailsViewModel {
                Shipment = shipment,
                DirectionsRequest = JsonConvert.SerializeObject(new DirectionsRequest {
                    Origin = shipment.Vehicle.PickUpPoint.Address.ToString(),
                    Destination = shipment.Vehicle.PickUpPoint.Address.ToString(),
                    WayPoints = wayPoints,
                    TravelMode = "DRIVING"
                })
            };

            return View("~/Views/Shipments/Details.cshtml", shipmentDetailsViewModel);
        }

        public async Task<IActionResult> Start(int? id) {
            if (id == null) {
                return NotFound();
            }

            var shipment = await _context.Shipments
                .Include(o => o.Vehicle)
                .SingleOrDefaultAsync(m => m.ShipmentId == id);
            if (shipment == null) {
                return NotFound();
            }

            if (shipment.ShipmentState == ShipmentState.ReadyToStartDelivery) {
                shipment.ShipmentState = ShipmentState.InDelivery;
            }

            if (shipment.ShipmentState == ShipmentState.ReadyToStartPickup) {
                shipment.ShipmentState = ShipmentState.InPickup;
            }

            shipment.Vehicle.VehicleState = VehicleState.OnShipment;

            _context.Shipments.Update(shipment);

            await _context.SaveChangesAsync();

            return RedirectToAction("Details", new {id = shipment.ShipmentId});
        }

        public async Task<IActionResult> End(int? id) {
            if (id == null) {
                return NotFound();
            }

            var shipment = await _context.Shipments
                .Include(o => o.PickUpOrders)
                .Include(o => o.DeliveryOrders)
                .Include(o => o.Vehicle)
                .SingleOrDefaultAsync(m => m.ShipmentId == id);
            if (shipment == null) {
                return NotFound();
            }

            if (shipment.ShipmentState == ShipmentState.InDelivery) {
                shipment.ShipmentState = ShipmentState.DeliveryDone;

                foreach (var shipmentDeliveryOrder in shipment.DeliveryOrders) {
                    shipmentDeliveryOrder.OrderState = OrderState.Delivered;
                }
            }

            if (shipment.ShipmentState == ShipmentState.InPickup) {
                shipment.ShipmentState = ShipmentState.PickupDone;

                foreach (var shipmentPickUpOrder in shipment.PickUpOrders) {
                    shipmentPickUpOrder.OrderState = OrderState.ReadyToBeDelivered;
                }
            }

            shipment.Vehicle.VehicleState = VehicleState.AtParkingLot;

            shipment.FinishDate = DateTime.UtcNow;

            _context.Shipments.Update(shipment);

            await _context.SaveChangesAsync();

            return RedirectToAction("Details", new {id = shipment.ShipmentId});
        }
    }
}

WebApplication/Controllers/PickUpShipmentsController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using PackageDelivery.Core;
using PackageDelivery.Data;
using PackageDelivery.Domain.Entities;
using PackageDelivery.Services.Services;
using PackageDelivery.WebApplication.Models;

namespace PackageDelivery.WebApplication.Controllers
{
    public class PickUpShipmentsController : Controller
    {
        private readonly PackageDeliveryContext _context;
        private readonly UserManager<User> _userManager;
        private readonly IShipmentManagementProvider _shipmentManagementProvider;

        public PickUpShipmentsController(IShipmentManagementProvider shipmentManagementProvider, PackageDeliveryContext context, UserManager<User> userManager) {
            _shipmentManagementProvider = shipmentManagementProvider;
            _context = context;
            _userManager = userManager;
        }

        [Authorize(Roles = UserRoles.MANAGER)]
        public async Task<IActionResult> Index() {
            var user = await _userManager.GetUserAsync(HttpContext.User);

            var packageDeliveryContext = _context.Shipments
                .Where(o => o.Vehicle.PickUpPointId == user.PickUpPointId && 
                (o.ShipmentState == ShipmentState.PickupDone ||
                o.ShipmentState == ShipmentState.InPickup ||
                o.ShipmentState == ShipmentState.ReadyToStartPickup ||
                o.ShipmentState == ShipmentState.WaitingForManagerApprovalToStartPickUp))
                .Include(s => s.User)
                .Include(s => s.PickUpOrders)
                .Include(s => s.Vehicle);

            return View("~/Views/Shipments/Index.cshtml", await packageDeliveryContext.ToListAsync());
        }

        [Authorize(Roles = UserRoles.MANAGER + "," + UserRoles.DRIVER)]
        // GET: Shipments/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var shipment = await _context.Shipments
                .Include(s => s.User)
                .Include(s => s.Vehicle)
                .ThenInclude(o => o.PickUpPoint.Address)
                .Include(s => s.PickUpOrders)
                .ThenInclude(o => o.PickUpAddress)
                .Include(s => s.PickUpOrders)
                .ThenInclude(o => o.DeliveryAddress)
                .SingleOrDefaultAsync(m => m.ShipmentId == id);
            if (shipment == null)
            {
                return NotFound();
            }

            var shipmentDetailsViewModel = new ShipmentDetailsViewModel {
                Shipment = shipment,
                DirectionsRequest = JsonConvert.SerializeObject(new DirectionsRequest {
                    Origin = shipment.Vehicle.PickUpPoint.Address.ToString(),
                    Destination = shipment.Vehicle.PickUpPoint.Address.ToString(),
                    WayPoints = shipment.PickUpOrders
                        .Select(o => new WayPoint { Location = o.PickUpAddress.ToString(), StopOver = true }).ToList(),
                    TravelMode = "DRIVING"
                })
            };

            return View("~/Views/Shipments/Details.cshtml", shipmentDetailsViewModel);
        }

        [Authorize(Roles = UserRoles.MANAGER)]
        // GET: Shipments/Details/5
        public async Task<IActionResult> Approve(int? id) {
            if (id == null) {
                return NotFound();
            }

            var shipment = await _context.Shipments
                .SingleOrDefaultAsync(m => m.ShipmentId == id);
            if (shipment == null) {
                return NotFound();
            }

            shipment.ShipmentState = ShipmentState.ReadyToStartPickup;
            _context.Shipments.Update(shipment);

            await _context.SaveChangesAsync();
            
            return RedirectToAction("Details", new {id = shipment.ShipmentId});
        }

        [Authorize(Roles = UserRoles.MANAGER)]
        // GET: Shipments/Details/5
        public async Task<IActionResult> Cancel(int? id) {
            if (id == null) {
                return NotFound();
            }

            var shipment = await _context.Shipments
                .SingleOrDefaultAsync(m => m.ShipmentId == id);
            if (shipment == null) {
                return NotFound();
            }

            shipment.ShipmentState = ShipmentState.WaitingForManagerApprovalToStartPickUp;
            _context.Shipments.Update(shipment);

            await _context.SaveChangesAsync();

            return RedirectToAction("Details", new {id = shipment.ShipmentId});
        }

        [Authorize(Roles = UserRoles.MANAGER)]
        // GET: Shipments/Create
        public async Task<IActionResult> Create()
        {
            var manager = await _userManager.GetUserAsync(HttpContext.User);

            var error = _shipmentManagementProvider.CreatePossibleShipments(
                ShipmentState.WaitingForManagerApprovalToStartPickUp, manager);

            TempData["InfoMessage"] = error.GetResult();

            return RedirectToAction("Index");
        }

        [Authorize(Roles = UserRoles.MANAGER)]
        // GET: Shipments/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var shipment = await _context.Shipments
                .Include(s => s.User)
                .Include(s => s.Vehicle)
                .SingleOrDefaultAsync(m => m.ShipmentId == id);
            if (shipment == null)
            {
                return NotFound();
            }

            return View("~/Views/Shipments/Delete.cshtml", shipment);
        }

        // POST: Shipments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = UserRoles.MANAGER)]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var shipment = await _context.Shipments
                .Include(s => s.User)
                .Include(s => s.Vehicle)
                .Include(s => s.PickUpOrders)
                .SingleOrDefaultAsync(m => m.ShipmentId == id);

            shipment.User = null;

            shipment.Vehicle.VehicleState = VehicleState.AtParkingLot;
            shipment.Vehicle = null;

            foreach (var shipmentPickUpOrder in shipment.PickUpOrders) {
                shipmentPickUpOrder.OrderState = OrderState.ReadyToBePickedUp;
            }
            shipment.PickUpOrders = null;

            _context.Shipments.Remove(shipment);
            await _context.SaveChangesAsync();

            return RedirectToAction("Index");
        }
    }
}

WebApplication/Views/Shared/_Layout.cshtml
@using System.Security.Claims
@using PackageDelivery.Core
@using PackageDelivery.Domain.Entities
@inject Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet JavaScriptSnippet
@inject SignInManager<User> SignInManager
@inject UserManager<User> UserManager

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    @Html.Raw(JavaScriptSnippet.FullScript)
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Package Delivery</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (SignInManager.IsSignedIn(User)) {
                        if (await UserManager.IsInRoleAsync(await UserManager.GetUserAsync(User), UserRoles.MANAGER)) {
                            <li><a asp-area="" asp-controller="PickUpShipments" asp-action="Index">Pickup Shipments</a></li>
                            <li><a asp-area="" asp-controller="DeliveryShipments" asp-action="Index">Delivery Shipments</a></li>
                        }
                        else if (await UserManager.IsInRoleAsync(await UserManager.GetUserAsync(User), UserRoles.DRIVER)) {
                            <li><a asp-area="" asp-controller="DriverShipments" asp-action="Index">Shipments</a></li>
                        }
                    }
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - Package Delivery</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>